const messages = [
  {
    role: "user",
    parts: [
      {
        text: "current balance for all click160",
      },
    ],
  },
  {
    role: "tool",
    parts: [
      {
        functionResponse: {
          name: "search_prod",
          response: {
            status: "success",
            error: "multiple_exist",
            data: [
              {
                ProdCd: "ACB160CBTN-MGB",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15591,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4009,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Black",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Black",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTR-MGB",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15748,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4009,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Black",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Black",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTS-MGB",
                barcodeCS: "",
                barcodePC: "",
                cCost: 108798,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 20780,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4009,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Black",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Black",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Pc/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTN-MSR",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15593,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4011,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Red",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Red",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTR-MSR",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15749,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4011,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Red",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Red",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTS-MSR",
                barcodeCS: "",
                barcodePC: "",
                cCost: 108798,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 20781,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4011,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Red",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Red",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Pc/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTR-WC",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15750,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4015,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 White",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "White",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTS-CS",
                barcodeCS: "",
                barcodePC: "",
                cCost: 108798,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 20779,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4010,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: "CLICK160 Silver",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Silver",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Pc/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTN-WC",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15592,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4015,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: "CLICK160 White",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "White",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
            ],
          },
        },
      },
    ],
  },
  {
    role: "tool",
    parts: [
      {
        functionResponse: {
          name: "get_prod_bal",
          response: {
            ixProd: "15591",
            ixBrch: 0,
            ixWH: "4282",
            ixWHSub: 0,
            SN: "",
            SN2: "",
            BN: "",
            qtyBAL: 2,
            qtyOUTFA: 0,
            qtyBALFA: 2,
          },
        },
      },
    ],
  },
  {
    role: "tool",
    parts: [
      {
        functionResponse: {
          name: "get_prod_bal",
          response: {
            ixProd: "15748",
            ixBrch: 0,
            ixWH: "4282",
            ixWHSub: 0,
            SN: "",
            SN2: "",
            BN: "",
            qtyBAL: 3,
            qtyOUTFA: 0,
            qtyBALFA: 3,
          },
        },
      },
    ],
  },
];

const initial = {
  contents: [
    {
      role: "user",
      parts: [
        {
          text: "current balance for all click160",
        },
      ],
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "search_prod",
            response: {
              status: "success",
              error: "multiple_exist",
              data: [
                {
                  ProdCd: "ACB160CBTN-MGB",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15591,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4009,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Black",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Black",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTR-MGB",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15748,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4009,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Black",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Black",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTS-MGB",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 108798,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 20780,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4009,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Black",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Black",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Pc/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTN-MSR",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15593,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4011,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Red",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Red",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTR-MSR",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15749,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4011,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Red",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Red",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTS-MSR",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 108798,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 20781,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4011,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Red",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Red",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Pc/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTR-WC",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15750,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4015,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 White",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "White",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTS-CS",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 108798,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 20779,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4010,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: "CLICK160 Silver",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Silver",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Pc/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTN-WC",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15592,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4015,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: "CLICK160 White",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "White",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
              ],
            },
          },
        },
      ],
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "get_prod_bal",
            response: {
              ixProd: "15591",
              ixBrch: 0,
              ixWH: "4282",
              ixWHSub: 0,
              SN: "",
              SN2: "",
              BN: "",
              qtyBAL: 2,
              qtyOUTFA: 0,
              qtyBALFA: 2,
            },
          },
        },
      ],
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "get_prod_bal",
            response: {
              ixProd: "15748",
              ixBrch: 0,
              ixWH: "4282",
              ixWHSub: 0,
              SN: "",
              SN2: "",
              BN: "",
              qtyBAL: 3,
              qtyOUTFA: 0,
              qtyBALFA: 3,
            },
          },
        },
      ],
    },
  ],
  tools: [
    {
      functionDeclarations: [
        {
          name: "search_prod",
          description: "Use this to search for specific products.",
          parameters: {
            type: "object",
            properties: {
              q: {
                type: "string",
                description: "The name or category of the product",
              },
            },
            required: ["q"],
          },
        },
        {
          name: "get_prod_bal",
          description:
            "Get the balance of a certain product. Only use this if the user specifically needs the balance of a certain product.",
          parameters: {
            type: "object",
            properties: {
              ixProd: {
                type: "integer",
                description: "The id of the product",
              },
              ixWH: {
                type: "integer",
                description: "Use 4282 as ixWH",
              },
            },
            required: ["ixProd"],
          },
        },
      ],
    },
  ],
};

const sec = {
  contents: [
    {
      role: "user",
      parts: [
        {
          text: "current balance for all click160 black",
        },
      ],
    },
    {
      parts: [
        {
          functionCall: {
            args: {
              ixProd: 15591,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
          thoughtSignature:
            "EtwCCtkCAb4+9vsW4kZ7ZS2LxnkSaitY0g0nFCp6EwiHV5IXbUHSIod+WFfIMCzdkevofUvOUHs1TDj8xp2VLI4JHKpP/dYKSy2gQ83AzAsMkEglLYoF1ujDao5vDZca2d/Woh2d+ZkJaaqZrfTjf5q/sr5/Tve1v2qREEJTP5YV6zuWKOusF9Hhf2iczl3S45+LryuzNQ0V1oM/x/fyIatKOxUzfBb0ukTkGO7szm9NGzV8756KnpAX6IUhdIYK/FIs1dkuqeMV4v58wf3NP9q0vQFxtc1FCm2AuCjOpdWDjN9i01dlTG2sMBTirSei+MZ1Sob/CUJCiGHHkBxvjq5ywyuoXbrocsUCFXZE25naE3a4w1hvQWE4EpJOTMTt5WvSc3Zgt6nJCie8k4SB15VQcAjjSD9K168gL7YZ1HkHh0zgqrIU3FNccd7WkcjmcyIKz4H4D7AQIYV6ktSM",
        },
        {
          functionCall: {
            args: {
              ixProd: 15748,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 20780,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
      ],
      role: "model",
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "get_prod_bal",
            response: {
              status: "success",
              data: {
                balance: 1,
              },
            },
          },
        },
      ],
    },
  ],
  tools: [
    {
      functionDeclarations: [
        {
          name: "search_prod",
          description: "Use this to search for specific products.",
          parameters: {
            type: "object",
            properties: {
              q: {
                type: "string",
                description: "The name or category of the product",
              },
            },
            required: ["q"],
          },
        },
        {
          name: "get_prod_bal",
          description:
            "Get the balance of a certain product. Only use this if the user specifically needs the balance of a certain product.",
          parameters: {
            type: "object",
            properties: {
              ixProd: {
                type: "integer",
                description: "The id of the product",
              },
              ixWH: {
                type: "integer",
                description: "Use 4282 as ixWH",
              },
            },
            required: ["ixProd"],
          },
        },
      ],
    },
  ],
};
