const messages = [
  {
    role: "user",
    parts: [
      {
        text: "current balance for all click160",
      },
    ],
  },
  {
    role: "tool",
    parts: [
      {
        functionResponse: {
          name: "search_prod",
          response: {
            status: "success",
            error: "multiple_exist",
            data: [
              {
                ProdCd: "ACB160CBTN-MGB",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15591,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4009,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Black",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Black",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTR-MGB",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15748,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4009,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Black",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Black",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTS-MGB",
                barcodeCS: "",
                barcodePC: "",
                cCost: 108798,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 20780,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4009,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Black",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Black",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Pc/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTN-MSR",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15593,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4011,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Red",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Red",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTR-MSR",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15749,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4011,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Red",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Red",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTS-MSR",
                barcodeCS: "",
                barcodePC: "",
                cCost: 108798,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 20781,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4011,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 Red",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Red",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Pc/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTR-WC",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15750,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4015,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: " CLICK160 White",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "White",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTS-CS",
                barcodeCS: "",
                barcodePC: "",
                cCost: 108798,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 20779,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4010,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: "CLICK160 Silver",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "Silver",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Pc/s",
                unitCS: "",
                unitSC: "",
              },
              {
                ProdCd: "ACB160CBTN-WC",
                barcodeCS: "",
                barcodePC: "",
                cCost: 114318,
                cPrice1: 0,
                cPrice2: 0,
                cPrice3: 0,
                cPrice4: 0,
                cPrice5: 0,
                importID: "",
                ixCat: 8,
                ixCatSub: 10,
                ixProd: 15592,
                ixProdSubLink1: 4021,
                ixProdSubLink2: 4015,
                ixProdSubLink3: 0,
                ixProdSubLink4: 0,
                ixProdSubLink5: 0,
                prodStatus: 1,
                qtyCS: 0,
                qtySC: 0,
                reqBN: 0,
                reqSN: 1,
                reqSN2: 1,
                sCat: "Units",
                sCatSub: "MC",
                sProd: "CLICK160 White",
                sProdCat: "Units",
                sProdSubLink1: "CLICK160",
                sProdSubLink2: "White",
                sProdSubLink3: null,
                sProdSubLink4: null,
                sProdSubLink5: null,
                unit: "Unit/s",
                unitCS: "",
                unitSC: "",
              },
            ],
          },
        },
      },
    ],
  },
  {
    role: "tool",
    parts: [
      {
        functionResponse: {
          name: "get_prod_bal",
          response: {
            ixProd: "15591",
            ixBrch: 0,
            ixWH: "4282",
            ixWHSub: 0,
            SN: "",
            SN2: "",
            BN: "",
            qtyBAL: 2,
            qtyOUTFA: 0,
            qtyBALFA: 2,
          },
        },
      },
    ],
  },
  {
    role: "tool",
    parts: [
      {
        functionResponse: {
          name: "get_prod_bal",
          response: {
            ixProd: "15748",
            ixBrch: 0,
            ixWH: "4282",
            ixWHSub: 0,
            SN: "",
            SN2: "",
            BN: "",
            qtyBAL: 3,
            qtyOUTFA: 0,
            qtyBALFA: 3,
          },
        },
      },
    ],
  },
];

const initial = {
  contents: [
    {
      role: "user",
      parts: [
        {
          text: "current balance for all click160",
        },
      ],
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "search_prod",
            response: {
              status: "success",
              error: "multiple_exist",
              data: [
                {
                  ProdCd: "ACB160CBTN-MGB",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15591,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4009,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Black",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Black",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTR-MGB",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15748,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4009,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Black",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Black",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTS-MGB",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 108798,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 20780,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4009,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Black",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Black",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Pc/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTN-MSR",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15593,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4011,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Red",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Red",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTR-MSR",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15749,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4011,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Red",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Red",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTS-MSR",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 108798,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 20781,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4011,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 Red",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Red",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Pc/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTR-WC",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15750,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4015,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: " CLICK160 White",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "White",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTS-CS",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 108798,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 20779,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4010,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: "CLICK160 Silver",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "Silver",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Pc/s",
                  unitCS: "",
                  unitSC: "",
                },
                {
                  ProdCd: "ACB160CBTN-WC",
                  barcodeCS: "",
                  barcodePC: "",
                  cCost: 114318,
                  cPrice1: 0,
                  cPrice2: 0,
                  cPrice3: 0,
                  cPrice4: 0,
                  cPrice5: 0,
                  importID: "",
                  ixCat: 8,
                  ixCatSub: 10,
                  ixProd: 15592,
                  ixProdSubLink1: 4021,
                  ixProdSubLink2: 4015,
                  ixProdSubLink3: 0,
                  ixProdSubLink4: 0,
                  ixProdSubLink5: 0,
                  prodStatus: 1,
                  qtyCS: 0,
                  qtySC: 0,
                  reqBN: 0,
                  reqSN: 1,
                  reqSN2: 1,
                  sCat: "Units",
                  sCatSub: "MC",
                  sProd: "CLICK160 White",
                  sProdCat: "Units",
                  sProdSubLink1: "CLICK160",
                  sProdSubLink2: "White",
                  sProdSubLink3: null,
                  sProdSubLink4: null,
                  sProdSubLink5: null,
                  unit: "Unit/s",
                  unitCS: "",
                  unitSC: "",
                },
              ],
            },
          },
        },
      ],
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "get_prod_bal",
            response: {
              ixProd: "15591",
              ixBrch: 0,
              ixWH: "4282",
              ixWHSub: 0,
              SN: "",
              SN2: "",
              BN: "",
              qtyBAL: 2,
              qtyOUTFA: 0,
              qtyBALFA: 2,
            },
          },
        },
      ],
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "get_prod_bal",
            response: {
              ixProd: "15748",
              ixBrch: 0,
              ixWH: "4282",
              ixWHSub: 0,
              SN: "",
              SN2: "",
              BN: "",
              qtyBAL: 3,
              qtyOUTFA: 0,
              qtyBALFA: 3,
            },
          },
        },
      ],
    },
  ],
  tools: [
    {
      functionDeclarations: [
        {
          name: "search_prod",
          description: "Use this to search for specific products.",
          parameters: {
            type: "object",
            properties: {
              q: {
                type: "string",
                description: "The name or category of the product",
              },
            },
            required: ["q"],
          },
        },
        {
          name: "get_prod_bal",
          description:
            "Get the balance of a certain product. Only use this if the user specifically needs the balance of a certain product.",
          parameters: {
            type: "object",
            properties: {
              ixProd: {
                type: "integer",
                description: "The id of the product",
              },
              ixWH: {
                type: "integer",
                description: "Use 4282 as ixWH",
              },
            },
            required: ["ixProd"],
          },
        },
      ],
    },
  ],
};

const sec = {
  contents: [
    [
      {
        role: "user",
        parts: [
          {
            text: "current balance for all click160",
          },
        ],
      },
    ],
    {
      parts: [
        {
          functionCall: {
            args: {
              ixProd: 15591,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
          thoughtSignature:
            "Eq8ECqwEAb4+9vtMys3w44AmLUEN6oDNZKJAnYKA6GNVZynF/blhVF+IUhn6tcVYmUXc16xLEuEPJ8tXTp4jO1vTRsrttSxdD+0uVFsqfcxlmXIboVKIp2CMp7j3Z6bkWIqpJDee3TGtaAwzpQI1zAyzvdKM4kkdMW+jze7Ohk/86L6NL9F1EZefdDsZNsDfioSrwxZGTOiBQFXJMAg8IynJncGKFNYojjEjDznGRDXc6pI2gy2bSywRFC7cWnXVEAOLERw08whC8Zxaq/E0BWuUCM96YOKq/KWEclRL/Hct1VS99STg0oUyHSoF4EJXv/GllUnNgCX+sE3HWzFARU1APNVgSXTl8KOhBSBY05TL7jbFHmurCWkIwyeM1Uir9CCV9AI+QkzAfgj085CpshF7WMsDzF1A+agCiJug9I0KxpuhHiJTwtqPUKf2920UVHDqhHKLm1pSCPa32f+VjuFveTrm0U2bzLYkiOAdWy93U2Tu7cUywOcpQGJy5lz2v5fw2UJsdfXyhTtj6nh0OyhwyB0+2yZ9XyNvzKCL8l50BOOSX7jEBp6HX3dXUqNmme57eJQFxhOu86c/uxnX1B95cR/TWF5zLQO+mfE2BNSdo+RKGyol4V7HPgpPc9X7K3J0jfkDhpsoFubnq7lNrPQh8Za3Re8Da78GyJcZAhAZ1AQ/0ydZ9sZ+Pxgc8Ei7b0sRWKW4+eRe9NScWrC0IapuLynY/nvx25e3lZF/2dZ0tw==",
        },
        {
          functionCall: {
            args: {
              ixProd: 15748,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 20780,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 15593,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 15749,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 20781,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 15750,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 20779,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
        {
          functionCall: {
            args: {
              ixProd: 15592,
              ixWH: 4282,
            },
            name: "get_prod_bal",
          },
        },
      ],
      role: "model",
    },
    {
      role: "tool",
      parts: [
        {
          functionResponse: {
            name: "get_prod_bal",
            response: {
              ixProd: "15591",
              ixBrch: 0,
              ixWH: "4282",
              ixWHSub: 0,
              SN: "",
              SN2: "",
              BN: "",
              qtyBAL: 2,
              qtyOUTFA: 0,
              qtyBALFA: 2,
            },
          },
        },
      ],
    },
  ],
  tools: [
    {
      functionDeclarations: [
        {
          name: "search_prod",
          description: "Use this to search for specific products.",
          parameters: {
            type: "object",
            properties: {
              q: {
                type: "string",
                description: "The name or category of the product",
              },
            },
            required: ["q"],
          },
        },
        {
          name: "get_prod_bal",
          description:
            "Get the balance of a certain product. Only use this if the user specifically needs the balance of a certain product.",
          parameters: {
            type: "object",
            properties: {
              ixProd: {
                type: "integer",
                description: "The id of the product",
              },
              ixWH: {
                type: "integer",
                description: "Use 4282 as ixWH",
              },
            },
            required: ["ixProd"],
          },
        },
      ],
    },
  ],
};
